name: Godot ANGLE static libs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
        # macOS and iOS
        - name: 🍎 macOS x86_64
          platform: macos
          os: macos-13
          xcode: "15.0"
          artifact-name: godot-angle-static-x86_64-macos-release
          artifact-path-angle: bin/libANGLE.macos.x86_64.a
          artifact-path-egl: bin/libEGL.macos.x86_64.a
          artifact-path-gles: bin/libGLES.macos.x86_64.a
          flags: arch=x86_64

        - name: 🍎 macOS arm64
          platform: macos
          os: macos-13
          xcode: "15.0"
          artifact-name: godot-angle-static-arm64-macos-release
          artifact-path-angle: bin/libANGLE.macos.arm64.a
          artifact-path-egl: bin/libEGL.macos.arm64.a
          artifact-path-gles: bin/libGLES.macos.arm64.a
          flags: arch=arm64

        - name: 🍏 iOS x86_64 simulator
          platform: ios
          os: macos-13
          xcode: "15.0"
          artifact-name: godot-angle-static-x86_64-ios-sim-release
          artifact-path-angle: bin/libANGLE.ios.x86_64.simulator.a
          artifact-path-egl: bin/libEGL.ios.x86_64.simulator.a
          artifact-path-gles: bin/libGLES.ios.x86_64.simulator.a
          flags: arch=x86_64 ios_simulator=yes

        - name: 🍏 iOS arm64 simulator
          platform: ios
          os: macos-13
          xcode: "15.0"
          artifact-name: godot-angle-static-arm64-ios-sim-release
          artifact-path-angle: bin/libANGLE.ios.arm64.simulator.a
          artifact-path-egl: bin/libEGL.ios.arm64.simulator.a
          artifact-path-gles: bin/libGLES.ios.arm64.simulator.a
          flags: arch=arm64 ios_simulator=yes

        - name: 🍏 iOS arm64 device
          platform: ios
          os: macos-13
          xcode: "15.0"
          artifact-name: godot-angle-static-arm64-ios-release
          artifact-path-angle: bin/libANGLE.ios.arm64.a
          artifact-path-egl: bin/libEGL.ios.arm64.a
          artifact-path-gles: bin/libGLES.ios.arm64.a
          flags: arch=arm64
        - name: Windows (arch=x86_64)
          platform: windows
          os: ubuntu-22.04
          artifact-name: godot-angle-static-x86_64-windows-release
          artifact-path-angle: bin/libANGLE.windows.x86_64.a
          artifact-path-egl: bin/libEGL.windows.x86_64.a
          artifact-path-gles: bin/libGLES.windows.x86_64.a
          flags: use_mingw=yes arch=x86_64 use_llvm=yes mingw_prefix=$HOME/llvm-mingw
          llvm: yes

        - name: Windows (arch=x86_32)
          platform: windows
          os: ubuntu-22.04
          artifact-name: godot-angle-static-x86_32-windows-release
          artifact-path-angle: bin/libANGLE.windows.x86_32.a
          artifact-path-egl: bin/libEGL.windows.x86_32.a
          artifact-path-gles: bin/libGLES.windows.x86_32.a
          flags: use_mingw=yes arch=x86_32 use_llvm=yes mingw_prefix=$HOME/llvm-mingw
          llvm: yes

        - name: Windows (arch=arm64)
          platform: windows
          os: ubuntu-22.04
          artifact-name: godot-angle-static-arm64-windows-release
          artifact-path-angle: bin/libANGLE.windows.arm64.a
          artifact-path-egl: bin/libEGL.windows.arm64.a
          artifact-path-gles: bin/libGLES.windows.arm64.a
          flags: use_mingw=yes arch=arm64 use_llvm=yes mingw_prefix=$HOME/llvm-mingw
          llvm: yes

        - name: Windows (arch=arm32)
          platform: windows
          os: ubuntu-22.04
          artifact-name: godot-angle-static-arm32-windows-release
          artifact-path-angle: bin/libANGLE.windows.arm32.a
          artifact-path-egl: bin/libEGL.windows.arm32.a
          artifact-path-gles: bin/libGLES.windows.arm32.a
          flags: use_mingw=yes arch=arm32 use_llvm=yes mingw_prefix=$HOME/llvm-mingw
        #   arm: true

    runs-on: ${{ matrix.os }}

    env:
      XCODE_DEV_PATH: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Select Xcode version
        if: ${{ matrix.platform == 'macos' || matrix.platform == 'ios' }}
        run: sudo xcode-select -switch "${XCODE_DEV_PATH}"

      - name: Install SCons (Native env)
        run: |
          python -m pip install scons==4.0.0

      - name: Install mako
        run: |
          python -m pip install mako

      - name: Install llvm-mingw
        if: ${{ matrix.platform == 'windows' }}
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz && \
          tar xf llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz
          rm -f llvm-mingw-*.xz
          mv llvm-mingw-* "$HOME/llvm-mingw"
          echo "$HOME/llvm-mingw/bin" >> $GITHUB_PATH

      # - name: Download and extract llvm-mingw SDK
      #   env:
      #     CURRENT_DIR: ${{ github.workspace }}
      #   run: |
      #     mkdir -p "$CURRENT_DIR/sdks"
      #     cd "$CURRENT_DIR/sdks"
      #     curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20241015/llvm-mingw-20241015-msvcrt-ubuntu-20.04-x86_64.tar.xz
      #     xz -dc llvm-mingw-20241015-msvcrt-ubuntu-20.04-x86_64.tar.xz | tar -xvf -
      #     rm -f llvm-mingw-20241015-msvcrt-ubuntu-20.04-x86_64.tar.xz
      #     cd llvm-mingw-20241015-msvcrt-ubuntu-20.04-x86_64
      #     echo "MINGW_PREFIX=$(pwd)" >> $GITHUB_ENV
      #     echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Prepare ANGLE source
        shell: bash
        run: |
          ./update_angle.sh

      - name: Build ANGLE
        run: |
          scons platform=${{ matrix.platform }} ${{ matrix.flags }} optimize=speed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            ${{ matrix.artifact-path-angle }}
            ${{ matrix.artifact-path-egl }}
            ${{ matrix.artifact-path-gles }}
          if-no-files-found: error

  release:
    name: 'Release'

    needs: [build]

    runs-on: ubuntu-latest

    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: ZIP Artifacts
        run: |
          for i in */; do (cd "${i%/}"; zip -r "../${i%/}.zip" .; cd ..); done

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          removeArtifacts: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          artifacts: "*.zip"
          artifactErrorsFailBuild: true
